# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    session:
        cookie_lifetime: 0      # La cookie muere al cerrar el navegador
        gc_maxlifetime: 3600    # La sesión en servidor caduca tras 1h de inactividad

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
